### ISSUE TITLE
building from source fails on 'configure'

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/m4port#12]
```
configure: error: <wchar.h> cannot be used with this compiler (xlclang -std=gnu11 -qascii -qnose -I/fultonm/dev/m4port/m4/lib,/fultonm/dev/m4port/patches/PR
1/include,/usr/include -DNSIG=9 -D_XOPEN_SOURCE=600 -D_ALL_SOURCE -D_OPEN_SYS_FILE_EXT=1 -D_AE_BIMODAL=1 -D_ENHANCED_ASCII_EXT=0xFFFFFFFF).
This is a known interoperability problem of glibc <= 2.5 with gcc >= 4.3 in
C99 mode. You have four options:
  - Add the flag -fgnu89-inline to CC and reconfigure, or
  - Fix your include files, using parts of
    <http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=b037a293a48718af30d706c2e18c929d0e69a621>, or
  - Use a gcc version older than 4.3, or
  - Don't use the flags -std=c99 or -std=gnu99.
 ```

**Comment by MikeFultonDev** [comment]
@ccw-1 @perry-ca Opinions on which of the four options to take?

**Comment by MikeFultonDev** [comment]
Seems like: `-fgnu89-inline` would be reasonable?

**Comment by perry-ca** [comment]
You have /usr/include in the -I.  The xlclang compiler should not be using the system headers in /usr/include.  It has it's own copy in /usr/include/le.

I can't reproduce the problem but in general don't specify -I/usr/include.

**Comment by MikeFultonDev** [comment]
@perry-ca I changed the code to use `/usr/include/le` and it didn't make a difference.
I also tried it with and without `-fgnu89-inline` and it didn't make a difference. 
@perry-ca would you be able to check this out and see if this is a problem in the xlclang compiler or if it's a problem in configure?

**Comment by MikeFultonDev** [comment]
not failing with this anymore
